### ISSUE TITLE
添加UFSDxe至APRIORI DXE区域时启动出现"Qualcomm Crashdump"

### ISSUE THREAD

**Issue by ghost** [Evsio0n/edk2sdm#2]
本人嵌入式开发小白一个，效仿edk2-pixel3和你的edk2sdm项目给小米9移植uefi固件，uefi shell已成功启动，但当我将XBL提取的UFSDxe驱动导入APRIORI DXE区域内，则出现qualcomm crashdump模式，然后重启。哪里错了，需要修改？UFS驱动不添加进APRIORI DXE区域能直接运行吗。

**Comment by Evsio0n** [comment]
请参考:
>https://evsio0n.com/archives/332/
注意:不属于该项目issue

**Comment by Evsio0n** [comment]
Closed for no responses, You can open at anytime when be active again.
