### ISSUE TITLE
Would love to contribute by being a tester for sd845 platform. 

### ISSUE THREAD

**Issue by TAOcroatia** [Evsio0n/edk2sdm#3]
I hope that in a near future this project will expand to sd845. If that's the case I'm willing to use my pocophone f1 as a test device.

**Comment by Evsio0n** [comment]
This is a project for MSM8998 (will as currently a long time) , So you may should visit some one other who will do more to figure it out. Like @LemonIces

**Comment by Tourniquet88** [comment]
Isn't it @Lemon1Ice ? But he did not publish anything yet.

**Comment by Evsio0n** [comment]
Yes it's him, So, it looks like this is not a issue for this project :)

**Comment by Evsio0n** [comment]
Closed for no responses, You can open at anytime when be active again.

**Comment by strongtz** [comment]
@TAOcroatia @Tourniquet88   Although it's a little off-topic here, but I would like to tell you that we now have a edk2 port for sdm845: edk2-porting/edk2-sdm845
